language: python

python:
  - "3.6"
  - "nightly"
  - pypy3

install:
  - python3 setup.py clean sdist bdist_wheel
  - pip3 --upgrade --force install pip setuptools
  - pip3 install .[tests]
  - pip3 install .

script:
  - vsh --version
  - pytest --cache-clear
