dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "nightly"

matrix:
  allow_failures:
  - python: nightly

install:
  - python -m pip install -U pip
  - python setup.py clean sdist bdist_wheel install
  - pip install --upgrade --force .[test]
  - pip install .

script:
  - python -m pytest --cache-clear -vvv -r a
