language: python

python:
  - "3.6"
  - "nightly"
  - pypy3

install:
  - python setup.py clean sdist bdist_wheel
  - pip install .[tests]
  - pip install .

script:
  - vsh --version
  - pytest --cache-clear
