language: python


services:
  - docker


script:
  - docker build -t vsh:test .
  - docker images
  - docker run --rm -it vsh:test vsh --version


after_success:
  - bash < (curl -s https://codecov.io/bash)
